version: "3"
services:
  redis-server:
    image: "redis" # <== This is already in the local docker hub
  node-app:
    restart: on-failure
    build: . # <== This is being built from the Dockerfile inside this app
    ports:
      - "5000:5000"
